export const techBadges = {
    React: "https://img.shields.io/badge/-React-red?style=flat-square&logo=react&logoColor=white",
    MongoDB: "https://img.shields.io/badge/-MongoDB-47A248?style=flat-square&logo=mongodb&logoColor=white",
    NodeJS: "https://img.shields.io/badge/-NodeJS-339933?style=flat-square&logo=node.js&logoColor=white",
    Python: "https://img.shields.io/badge/-Python-blue?style=flat-square&logo=python&logoColor=white",
    Numpy: "https://img.shields.io/badge/-NumPy-013243?style=flat-square&logo=numpy&logoColor=white",
    Pandas: "https://img.shields.io/badge/-Pandas-150458?style=flat-square&logo=pandas&logoColor=white",
    Netlify: "https://img.shields.io/badge/-Netlify-00C7B7?style=flat-square&logo=netlify&logoColor=white",
    Appwrite: "https://img.shields.io/badge/-Appwrite-F02E65?style=flat-square&logo=appwrite&logoColor=white",
    TailwindCSS: "https://img.shields.io/badge/-TailwindCSS-38B2AC?style=flat-square&logo=tailwind-css&logoColor=white",
    NativeWind: "https://img.shields.io/badge/-NativeWind-063990?style=flat-square&logo=react&logoColor=white",
    JavaScript: "https://img.shields.io/badge/-JavaScript-F7DF1E?style=flat-square&logo=javascript&logoColor=black",
    Sklearn: "https://img.shields.io/badge/-Sklearn-F7931E?style=flat-square&logo=scikit-learn&logoColor=white",
    Scipy: "https://img.shields.io/badge/-SciPy-8CAAE6?style=flat-square&logo=scipy&logoColor=white",
    SQL: "https://img.shields.io/badge/-SQL-003B57?style=flat-square&logo=postgresql&logoColor=white",  // Using PostgreSQL for SQL
    XAMPP: "https://img.shields.io/badge/-XAMPP-FB7A24?style=flat-square&logo=xampp&logoColor=white",
    phpMyAdmin: "https://img.shields.io/badge/-phpMyAdmin-6C78AF?style=flat-square&logo=phpmyadmin&logoColor=white",
    HTML: "https://img.shields.io/badge/-HTML5-E34F26?style=flat-square&logo=html5&logoColor=white",
    CSS: "https://img.shields.io/badge/-CSS3-1572B6?style=flat-square&logo=css3&logoColor=white",
    ROS: "https://img.shields.io/badge/-ROS-22314E?style=flat-square&logo=ros&logoColor=white",
    Arduino: "https://img.shields.io/badge/-Arduino-00979D?style=flat-square&logo=arduino&logoColor=white",
    C: "https://img.shields.io/badge/-C++-00599C?style=flat-square&logo=c%2B%2B&logoColor=white",
    TypeScript: "https://img.shields.io/badge/typescript-007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white",
    Gatsby: "https://img.shields.io/badge/gatsby-663399.svg?style=for-the-badge&logo=gatsby&logoColor=white",
    GDScript: "https://img.shields.io/badge/gdscript-478CBF.svg?style=for-the-badge&logo=godot-engine&logoColor=white",
    GoDot: "https://img.shields.io/badge/godot-478CBF.svg?style=for-the-badge&logo=godot-engine&logoColor=white",
  };
  